= Create Table Statement

== DRAFT

.TODOs
- [ ] create type
- [ ] optional fields
- [ ] table options

A table is a collection of some type with zero or more constraints.

.Example
[source,rql]
----
-- equivalent (no-schema)
create table points;
create table points ();
create table points ({...})

create type point {
    x: number,
    y: number,
};

create table points (point);

create table points (point, { key: x });

create table points ({
    x: number,
    y: number,
    z: number|null  -- nullable
    ...             -- open content
}, {
    hash: x,
    sort: y,
});
----

== Syntax

[source,mckeeman]
----
create_table
    "create" "table" table_definition

table_definition
    table_name
    table_name "(" ")"
    table_name "(" table_body ")"

table_name
    identifier 

table_body
    table_schema
    table_schema "," table_options

table_schema
    type_definition

type_definition
    "{ }"
    "{ type_members }"

type_members
    type_member
    type_member "," type_member

type_member
    identifier ":" type

table_options
    "{ table_option }"

table_option
    identifier ":" value
----

== Rules

. A table 
// . A table MAY have a _key_ member OR _hash/sort_ members.
// . A table MUST NOT have a _hash_ member without a _sort_ member.
// . A table MUST NOT have a _key_ member and _hash/sort_ members.
// . If a member has one of the key constraints, then _<constraint_not_null>_ is implicit.
. A member is "NOT NULL" by default.
. A member with type T MAY be declared nullable by appending a `|null` to the column type definition.
. If a table with the given name already exists, raise an error — i.e. the IF NOT EXISTS clauses is not supported.
. 

== Ideas

. Like MongoDB,  and DynamoDB
. Does the concept of hash/sort even make sense .. seems a sort key is all that's needed.
. Consider derived keys.
. Consider using typescript for type definitions.
. Column constraints are redundant, so constraints will only be modeled as table constraints.
. The type of a column is a type definition like typescript, but I am starting simple and only allowing "|null" to model the "[NOT] NULL" column constraint.
. Consider a "with properties" clause to the create table.
* There are three types of tables:
** K-Table - unique primary key, backed by a kv-store.
** HS-Tables - hash and sort keys, backed by b-trees.
** Other - unsorted collections, backed by ??

[source]
----
type foo = {
    x: number,
    y: number,
    [key: string]: any,
};

-- equivalent

type foo = {
    x: number,
    y: number,
    ...
};
----
