[package]
name = "monadb"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib", "cdylib"]

[features]
python = ["dep:pyo3"]

[build-dependencies]
lalrpop = "0.21.0"
serde = {version = "1", features = ["derive"]}
serde_yaml = "0.9"

[dependencies]
bytes = "1.9.0"
heed = "0.22.1"
lalrpop-util = {version = "0.21.0", features = ["lexer", "unicode"]}
logos = "0.14.2"
serde = {version = "1.0", features = ["derive"]}
serde_json = {version = "1.0", features = ["preserve_order"]}
tempfile = "3.14.0"
pyo3 = {version = "0.23", optional = true, features = [
    "extension-module",
    "abi3-py39",
]}

[dev-dependencies]
hegeltest = "0.18"
serde = {version = "1", features = ["derive"]}
serde_yaml = "0.9"
tempfile = "3.14.0"

[lints.clippy]
missing_errors_doc = "allow"
pedantic = {level = "warn", priority = -1}
must_use_candidate = "allow"
