base_url = "https://rchowell.github.io/MonaDB"
title = "MonaDB"
compile_sass = false
generate_feeds = false
minify_html = false

[markdown]
render_emoji = false

[extra]
github = "https://github.com/rchowell/MonaDB"
