== File Format

_This section will describe the file format._

For now, ignore a db header and let's focus on a single table.

.Header
|===
| Offset | Size | Description
| 0      | 3    | "RHO"
| 3      | 4    | i64 version
| 7      | 4    | i64 page size
|===

.Notes
- Should probably store as BSON or CBOR?

== Types

.link:https://www.json.org/json-en.html[JSON Reference]
* object
* string
* number
* boolean
* null

== Schemas

_This section will describe how schemas are stored and modified._

Schemas are stored in a table called _schema_ defined by the following RQL (SQL-ish).

[source,sql]
----
CREATE TABLE schema (
    type string,    /* TABLE, VIEW, INDEX, etc. */
    name string,    /* Object name */
    rql string,     /* Object schema */
    ptr number,     /* Pointer to root table page */
)
----

.Notes
- Consider "objects" rather than "schemas".
- Consider prefixing with _ to avoid conflicts with user tables.
- Beam has link:https://github.com/apache/beam/tree/master/sdks/java/testing/tpcds/src/main/resources/schemas[TPC schemas as Avro JSON].

== RQL

_This section will describe the RQL language._

RQL is SQL (ish).

.Notes
- When deciding on language features, I will lean on JS before SQL.

== Other

- Website with playground and dead simple language documentation.
- REPL
- Insert semantics?
    - If you insert an object into a "closed" table, the extra fields are ignored.
    - If you insert an object into an "open" table, the extra fields are stored in a hidden object column.
- Notes optimizations such as page compaction.
