== Usage

I would like rho to be a library with several applications:

- Library like sqlite.
- Server like Redis.
- CLI tool like jq/awk/other.
- Shell like sqlite repl.

== Catalog

The catalog provides all access to schemas and tables. It is backed by sqlite so that I do not have to solve 

.Operations
- create_table
- drop_table
- insert

== Types

.link:https://www.json.org/json-en.html[JSON Reference]
* object
* string
* number
* boolean
* null

.Notes
- Consider prefixing with _ to avoid conflicts with user tables.
- Beam has link:https://github.com/apache/beam/tree/master/sdks/java/testing/tpcds/src/main/resources/schemas[TPC schemas as Avro JSON].

== RQL

_This section will describe the RQL language._

RQL is SQL (ish).

.Notes
- When deciding on language features, I will lean on JS and Lua before SQL.

== Other

- Website with playground and dead simple language documentation.
- REPL
- Insert semantics?
    - If you insert an object into a "closed" table, the extra fields are ignored.
    - If you insert an object into an "open" table, the extra fields are stored in a hidden object column.
- Notes optimizations such as page compaction.

== RHO 2

== File Format (RHO2)

_This section will describe the file format._

For now, ignore a db header and let's focus on a single table.

.Header
|===
| Offset | Size | Description
| 0      | 3    | "RHO"
| 3      | 4    | i64 version
| 7      | 4    | i64 page size
|===

.Notes
- Should probably store as BSON or CBOR?

== Schemas

_This section will describe how tables schemas are stored and modified._

Schemas are stored in a table called _catalog_ defined by the following RQL (SQL-ish).

[source,sql]
----
CREATE TABLE catalog (
    kind string,    /* TABLE, VIEW, INDEX, etc. */
    name string,    /* Object name */
    rql string,     /* Object schema */
    ptr number,     /* Pointer to root table page */
)
----