= Cask

The cask is a modified bitcask as a single file representing several key-value bins.

== Format

The cask format is composed of a head, body, and tail.

=== Head

.Head
|===
| Field | Offset | Size | Description

| Magic      |     0 | 4 | MONA
| Version    |     4 | 1 | A u8 version

|===

=== Body

The body is the compacted record set which does not exist yet.

=== Tail

The tail is the appendable active record set.

.Record
|===
| Field | Offset | Size | Description

| Flag      |     0 | 1 | A u8 bit-flag
| Size(Key)  |     1 | 1 | A u8 size in bytes (N)
| Size(Val)  |     2 | 2 | A u16 size in bytes (M)
| Key  |     4 | N | Record key bytes
| Val  |   4+N | M | Record val bytes

|===

.Rules
- If the highest-order bit is 1, then it's a tombstone.
- The next 7 bits are an unsigned integer indicating the bin (127 max bins).
- The key can have a max size of 256 bytes (u8).
- The val can have a max size of 64 kilobytes (u16).

== Synchronize

The algorithm to synchronize (restore) the cask map is roughly,

```python
def restore(file) -> dict:
    map = {}
    while not end:
        pos = file.pos()
        // read prefix
        k_size = file.read(2) as u16
        v_size = file.read(8) as u64
        key = file.read(k_size) as bytes
        // skip value
        file.seek(v_size)
        // set pointer
        map[key] = Pointer(pos, file.pos() - pos)
    return map
```

== Notes

* Not using bincode to reduces deps.
* Consider making MAX_KEY_LENGTH configurable (u16).
* Consider mkaing MAX_VAL_LENGTH configurable (u64).