Transforms using simplified SQL verbs for familiarity.

> mindsent: "we mostly support the familiar SQL thing, but prefer this" ??

.Operations
|===
| Clause | Action |

| select | map
| with   | map
| from   | iterate
| where  | filter
| group  | reduce
| order  | sort
| fetch  | limit/offset
| step   | step
|===

.Loop
[source]
----
select sum, y
   from points p
   where  p.x > 10
   group  sum(p.z) sum, p.y y
   order  p.z
   fetch  50..100

select sum, y
   from   points p, locations l
   with   p.x as x, l.y as y
   where  x = y and x > 10
   group  sum(p.z) as sum, p.y as y
   order  z asc
   fetch  50..100

-- don't forget union, intersect, except!
----

.Refs
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array
* https://docs.oracle.com/javase/8/docs/api/?java/util/stream/Stream.html
* https://doc.rust-lang.org/std/iter/trait.Iterator.html

== Intermediate Representation

* Tree IR is easy to build from the parser.
* Compiler needs to flatten the tree to something more linear for codegen.
* Language is functional-like.
* Parser is tree-like.
* IR is a block tree; where each block makes imperative codegen easier.
* Codegen wants a linear, imperative representation.

== Basic Operations

[source]
----
-- assignment
1 as x;

-- casts

1::int      -- -> cast(1 as int)
2::double   -- -> cast(2 as int)
3::string   -- -> cast(3 as string)
----

== Deleting Rows

Here is some design for basic row deletions using the MonaDB VM, then invoking SQLite. This may reach a scaling limit (tbd), but it's a start - and I could always batch deletes in an SQLite transaction.

[source]
----
-- input
delete from T where predicate(t);

-- Step 1. execute predicate in MonaDB.
let oids = exec(select oid from T where predicate(t)).collect();

-- Step 2. execute deletions in sqlite.
delete from T where oid in $oids;
----

.Idea
* scan with oid (have locals stack with oid/value pairs)
* each local holds its oid
