= Design Note - Cursor

A _cursor_ is a seekable reference to a table, used by the virtual machine, with four primary actions.

|===
| Action    | Description

| next      | advances the cursor to the next position
| rewind    | moves the cursor to the first position
| seek      | moves the cursor to a specific position
| curr      | returns &row at current position
|===

NOTE: like C file I/O and the SQLite VM cursor

== Looping

.Input
[source,sql]
----
... from t
----

.Instructions
[source]
----
| PC  | INSTRUCTION | NOTE
+-----+-------------+-----------
| 0   | open        |
| 1   | rewind      | if empty, jump to n+1
| 2   |  (loop)     |
| ..  |             |
| n   | next        | if next, jump to 2
| n+1 | ...         |   
----

== Producing a Value

* The compiler resolves variables to the source cursor index.
* The compiler emits a _load(n)_ instruction which is effectively `stack.push(cursor[n].curr())`

== Fetch Instructions

The fetch instruction is implemented as a pair of instructions: cnt_if_pos and cnt_if_zero.
The cnt_if_pos instruction is placed at the top of the loop; it decrements the counter and jumps if the counter is positive. This allows skipping the loop without performing any work. The cnt_if_zero instruction is placed at the end of the loop; it decrements the counter and if the counter is zero, the loop is exited.
Counters are u64s held in the VM state which are initialized before entering the loop.

.Instructions
* cnt_set
* cnt_if_pos
* cnt_if_zero

.Example
[source]
----
| PC  | INSTRUCTION  | NOTE
+-----+--------------+-----------
| 1   | rewind       | if empty, jump to n+1
| 2   |  cnt_if_pos  | c--, jump if c > 0
| ..  |              |   
| ..  |  (loop)      |   
| ..  |  cnt_if_zero | c--, jump if c = 0
| n   | Next         | if next, jump to 2
----
