== Open Questions
- Consider using the top-level function name as the alias name
- What about top-level single values and subquery coercion?
- Consider multiple backends (SQLite, Redis, Rho file, Rho memory).

== Closed Questions

. Why not compile to Lua or SQLite bytecode? (missing operations eventual perf??)
.. A. Eventual go is no deps or stdlib.
. Q. Look into macros vs inline functions (premature??).
.. A. Don't worry about it.

== Usage

I would like rho to be a library with several applications:

- Library like sqlite.
- Server like Redis.
- CLI tool like jq/awk/other.
- Shell like sqlite repl.

== What's in a Name?

- monadb
- Named after my cat
- Alludes to mongo (and monetdb)
- Reads nice like duckdb

== Rho

Rho should be renamed to "Connection"; it holds the inner connection ("catalog") which provides access to the underlying storage.

== Catalog

The catalog provides all access to schemas and tables. It is backed by sqlite so that I do not have to implement the storage backend .. yet.

== Types

* Object
* String
* Number
* Boolean

> See link:https://www.json.org/json-en.html[JSON Reference]

.Notes
- Consider prefixing with _ to avoid conflicts with user tables.
- Beam has link:https://github.com/apache/beam/tree/master/sdks/java/testing/tpcds/src/main/resources/schemas[TPC schemas as Avro JSON].

== Values

Why must I write my own value representation .. why not use serde_json?

== Tables

There are three types of tables:

* K-Table - unique primary key, backed by a kv-store.
* HS-Tables - hash and sort keys, backed by b-trees.
* Other - unsorted collections, backed by ??

=== K-Table

A k-table is a table with a singular primary key

== Appendices


== File Format (RHO2)

_This section will describe the file format._

For now, ignore a db header and let's focus on a single table.

.Header
|===
| Offset | Size | Description
| 0      | 3    | "RHO"
| 3      | 4    | i64 version
| 7      | 4    | i64 page size
|===

.Notes
- Should probably store as BSON or CBOR?

== Schemas

_This section will describe how tables schemas are stored and modified._

Schemas are stored in a table called _catalog_ defined by the following RQL (SQL-ish).

[source,sql]
----
CREATE TABLE catalog (
    kind string,    /* TABLE, VIEW, INDEX, etc. */
    name string,    /* Object name */
    rql string,     /* Object schema */
    ptr number,     /* Pointer to root table page */
)
----

== Brainstorming

- Website with playground and dead simple language documentation.
- REPL
- Insert semantics?
    - If you insert an object into a "closed" table, the extra fields are ignored.
    - If you insert an object into an "open" table, the extra fields are stored in a hidden object column.
- Optimizations such as page compaction.

== Advice

> Take the extra time you saved not rewriting your parsing code and spend it improving the compile error messages your compiler shows users. Good error handling and reporting is more valuable to users than almost anything else you can put time into in the front end. - Bob Nystrom
