use std::str::FromStr;
use lalrpop_util::ParseError;
use crate::error::Error;
use crate::compiler::Compiler;
use crate::ir;
use crate::lexer::Token;
use crate::value::Value;

grammar;

extern {
    type Location = usize;
    type Error = Error;

    enum Token {
        // symbols
        ","         => Token::Comma,
        ":"         => Token::Colon,
        "..."       => Token::Ellipsis,
        "."         => Token::Period,
        ";"         => Token::SemiColon,
        "*"         => Token::Star,
        "("         => Token::ParenL,
        ")"         => Token::ParenR,
        "{"         => Token::BraceL,
        "}"         => Token::BraceR,
        "["         => Token::BracketL,
        "]"         => Token::BracketR,
        // keywords
        "as"        => Token::As,
        "create"    => Token::Create,
        "delete"    => Token::Delete,
        "drop"      => Token::Drop,
        "from"      => Token::From,
        "insert"    => Token::Insert,
        "into"      => Token::Into,
        "select"    => Token::Select,
        "table"     => Token::Table,
        // types
        "t_bool"    => Token::TypeBool,
        "t_number"  => Token::TypeNumber,
        "t_string"  => Token::TypeString,
        "t_object"  => Token::TypeObject,
        "t_array"   => Token::TypeArray,
        "t_any"     => Token::TypeAny,
        // literals
        "null"      => Token::Null,
        "true"      => Token::True,
        "false"     => Token::False,
        "number"    => Token::Number(<f64>),
        "string"    => Token::String(<String>),
        // names and identifiers
        "ident"     => Token::Identifier(<String>),
    }
}

pub Rql = <Statement> ";";

Statement: ir::Statement = {
    Create  => ir::Statement::Create(<>),
    Delete  => ir::Statement::Delete(<>),
    Drop    => ir::Statement::Drop(<>),
    Insert  => ir::Statement::Insert(<>),
    Select  => ir::Statement::Select(<>),
};

Create: ir::Create = {
    "create" "table" <Ident> "(" <TableMembers> ")" => ir::create_table(<>)
};

TableMembers: Vec<ir::TableMember> = List<TableMember>;

TableMember: ir::TableMember = <Ident> <Type> => ir::table_member(<>);

Select: ir::Select = {
    "select" "*"                <From>  => ir::select_star(<>),
    "select" "{" <Members> "}"  <From>  => ir::select_list(<>),
    "select" <List<SelectItem>> <From>  => ir::select_list(<>),
};

SelectItem: ir::Member = {
    <Path>              => ir::select_path(<>),
    <Expr> "as" <Ident> => ir::select_item(<>),
}

From: ir::From = {
    "from" <Ident>              => ir::from_no_alias(<>),
    "from" <Ident> "as" <Ident> => ir::from(<>)
}

Insert: ir::Insert = {
    "insert" "into" <InsertTarget> <InsertSource> => ir::insert(<>),
}

InsertTarget: String = Ident;

InsertSource: Vec<ir::Obj> = {
    InsertValue     => vec![<>],
    InsertValues    => <>,
};

InsertValue: ir::Obj = "{" <Members> "}";

InsertValues: Vec<ir::Obj> = "[" <List<InsertValue>> "]";

// TODO
Delete: String = "delete" "from" <Ident>;

// TODO
Drop: String = "drop" "table" <Ident>;

//------------------------------
// TYPES
//------------------------------

Type: ir::Type = {
    "t_bool"    => ir::Type::Bool,
    "t_number"  => ir::Type::Number,
    "t_string"  => ir::Type::String,
    "t_object"  => ir::Type::Object,
    "t_array"   => ir::Type::Array,
    "t_any"     => ir::Type::Any,
};

//------------------------------
// EXPRESSIONS
//------------------------------

Expr: ir::Expr = {
    Ident                   => ir::expr_var(<>),
    Value                   => ir::expr_lit(<>),
    <Expr> "[" <Expr> "]"   => ir::expr_jpe(<>),
    <Expr> "." <Ident>      => ir::expr_jpk(<>),
    "{" <Members> "}"       => ir::expr_obj(<>),
    "(" <Expr> ")"          => <>,
};

Path: ir::Expr = {
    Ident               => ir::expr_var(<>),
    <Expr> "." <Ident>  => ir::expr_jpk(<>),
};

Members: Vec<ir::Member> = List<Member>;

Member: ir::Member = {
    Path                    => ir::member_path(<>),
    <"ident">  ":" <Expr>   => ir::member_assign(<>),
    <"string"> ":" <Expr>   => ir::member_assign(<>),
    "..." <Expr>            => ir::member_spread(<>),
}

Value: Value = {
    "null"      => Value::null(),
    "true"      => Value::bool(true),
    "false"     => Value::bool(false),
    "number"    => Value::number(<>),
    "string"    => Value::string(<>),
};

Ident: String = "ident";

//------------------------------
// MACROS
//------------------------------

List<T>: Vec<T> = {
    <mut v:(<T> ",")*> <e:T?> => match e {
        None => v,
        Some(e) => {
            v.push(e);
            v
        }
    }
};
